server:
  port: 8082
  context-path: /RSEMSServer

#
#  logging:
#  config: classpath:log4j2.xml


# jdbc_config
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: LHT
    password: LHT
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    validationQuery: SELECT 'x'
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    # 合并多个DruidDataSource的监控数据
    #spring.datasource.useGlobalDataSourceStat=true

# mybatis_config
mybatis:
    mapper-locations: classpath*:mapper/**/*.xml
    typeAliasesPackage: cn.rails.rsems.model
logging:
  path: C:\Users\macAdministrator\Desktop\
  file: log.log


#======
myProps: #自定义的属性和值
  listProp1:
#  simpleProp: simplePropValue
#  arrayProps: 1,2,3,4,5

    - name: abc
      value: abcValue
    - name: efg
      value: efgValue
  userUrl:
    - /user/test
    - /pown
#notUrl:

#  mapProps:
#    key1: value1
#    key2: value2
